[project]
name = "decrypt-otpauth"
version = "0.1.0"
description = "TODO"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cryptography==46.0.3",
    "pillow==12.0.0",
    "qrcode==8.2",
]

[dependency-groups]
lint = [
    "pre-commit==4.4.0",
    "ruff==0.14.6",
]
dev = [
    "pytest==9.0.0",
]
